### ISSUE TITLE
How to use LLM to create CAD file like your input?

### ISSUE THREAD

**Issue by stu-github** [neka-nat/cad3dify#2]
I want to use LLM to create the programmatic code, which can make CAD file like your input, do you have any suggestions? 
How to achieve this goal?

**Comment by neka-nat** [comment]
The discussion here might be helpful.
https://github.com/neka-nat/cad3dify/issues/1#issuecomment-2431610903

**Comment by stu-github** [comment]
> The discussion here might be helpful. [#1 (comment)](https://github.com/neka-nat/cad3dify/issues/1#issuecomment-2431610903)

Thanks
